import { describe, expect, test } from 'vitest';
import { compileCode } from '../../modules/interpreter';

describe('MVP interpreter', () => {
  test('compiles movement commands and repeat blocks', () => {
    const result = compileCode('move_forward()\nrepeat(5): move_right', [
      'move_forward',
      'move_right',
      'repeat',
    ]);

    expect(result).toMatchObject({
      success: true,
      commands: ['move_forward', 'repeat(5): move_right'],
    });
  });

  test('rejects unknown commands with a child-friendly message', () => {
    const result = compileCode('fly()', ['move_forward']);

    expect(result.success).toBe(false);
    expect(result.success ? '' : result.error).toContain('komutu tanimiyorum');
  });

  test('rejects commands that are not available in the current level', () => {
    const result = compileCode('move_down()', ['move_forward']);

    expect(result.success).toBe(false);
    expect(result.success ? '' : result.error).toContain('bu seviyede kullanilamaz');
  });

  test('allows repeat counts needed by wider boards', () => {
    const result = compileCode('repeat(9): move_right', ['repeat', 'move_right']);

    expect(result).toMatchObject({
      success: true,
      commands: ['repeat(9): move_right'],
    });
  });

  test('rejects repeat counts outside the MVP range', () => {
    const result = compileCode('repeat(25): move_right', ['repeat', 'move_right']);

    expect(result.success).toBe(false);
    expect(result.success ? '' : result.error).toContain('1 ile 24');
  });

  test('compiles condition blocks when available', () => {
    const result = compileCode('if obstacle_ahead(): move_up', ['if_obstacle_ahead', 'move_up']);

    expect(result).toMatchObject({
      success: true,
      commands: ['if obstacle_ahead(): move_up'],
    });
  });

  test('compiles variables and arithmetic expressions', () => {
    const result = compileCode('steps = 2 + 1\nmove_right(steps)', [
      'assignment',
      'operator',
      'move_right',
    ]);

    expect(result).toMatchObject({
      success: true,
      commands: ['move_right(3)'],
    });
  });

  test('compiles inline arithmetic in movement step fields', () => {
    const result = compileCode('move_right(1 + 2)', ['move_right']);

    expect(result).toMatchObject({
      success: true,
      commands: ['move_right(3)'],
    });
  });

  test('compiles repeat blocks that use a steps expression', () => {
    const result = compileCode('steps = 1 + 2\nrepeat(2): move_right(steps)', [
      'assignment',
      'operator',
      'repeat',
      'move_right',
    ]);

    expect(result).toMatchObject({
      success: true,
      commands: ['move_right(3)', 'move_right(3)'],
    });
  });

  test('compiles if else blocks with expression conditions', () => {
    const result = compileCode('steps = 3\nif steps > 2:\n  move_right(steps)\nelse:\n  move_up()', [
      'assignment',
      'operator',
      'if_else',
      'move_right',
      'move_up',
    ]);

    expect(result).toMatchObject({
      success: true,
      commands: ['move_right(3)'],
    });
  });

  test('compiles inline runtime if else generated by blocks', () => {
    const result = compileCode('if item_here(): pick_item() else: move_right()', [
      'if_else',
      'pick_item',
      'move_right',
    ]);

    expect(result).toMatchObject({
      success: true,
      commands: ['if item_here(): pick_item else: move_right'],
    });
  });

  test('compiles while loops with a guarded counter', () => {
    const result = compileCode('steps = 3\nwhile steps > 0:\n  move_right()\n  steps = steps - 1', [
      'assignment',
      'operator',
      'while',
      'move_right',
    ]);

    expect(result).toMatchObject({
      success: true,
      commands: ['move_right', 'move_right', 'move_right'],
    });
  });

  test('compiles for range and match case blocks', () => {
    const result = compileCode('route = \"right\"\nfor i in range(2):\n  match route:\n    case \"right\":\n      move_right()\n    case _:\n      move_up()', [
      'assignment',
      'for_range',
      'match_case',
      'move_right',
      'move_up',
    ]);

    expect(result).toMatchObject({
      success: true,
      commands: ['move_right', 'move_right'],
    });
  });
});
